<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EmailSeeder extends Seeder
{
    public function run(): void
    {
        $emails = [
            [
                'milestone_id' => 1,
                'phase_id' => 1,
                'subject' => 'Project Activation',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Project Activation Phase \n\n🚀 Your project officially begins! We gather all essential details, understand your goals, and align expectations. This includes reviewing your brand, business needs, and planned timelines.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 1,
                'phase_id' => 2,
                'subject' => 'Site Architecture & Analysis',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Site Architecture & Analysis Phase \n\n🚀 We map out your website\'s structure, identify all required pages, and assign team members to each key area to ensure a smooth development process.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 2,
                'phase_id' => 3,
                'subject' => 'Template Design Creation',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Template Design Creation Phase \n\n🚀 Our designers create two initial layout options — a homepage and one internal page — based on your branding and vision.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 2,
                'phase_id' => 4,
                'subject' => 'Template Review and approval from UI Lead',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Template Review and Approval from UI Lead Phase \n\n🚀 We perform an internal quality review to ensure the design meets our standards before presenting it to you.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 3,
                'phase_id' => 5,
                'subject' => 'Template Design Review/Approval',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Template Design Review/Approval Phase \n\n🚀 We present the design concepts to you for feedback and final direction. This ensures the visual style aligns with your goals.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 3,
                'phase_id' => 6,
                'subject' => 'Client Design comments',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Client Design Comments Phase \n\n🚀 We apply your feedback to fine-tune the design and make sure everything looks and feels just right before we proceed.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 4,
                'phase_id' => 7,
                'subject' => 'Internal Pages Mockup Creation',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Internal Pages Mockup Creation Phase \n\n🚀 We design the full internal pages of your site using the approved visual direction and layout.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 5,
                'phase_id' => 8,
                'subject' => 'Project Plan and Project Discussion Documentation',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Project Plan & Discussion Documentation Phase \n\n🚀 We finalize the scope, timeline, and deliverables, and document everything clearly for your reference and transparency.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 6,
                'phase_id' => 9,
                'subject' => 'Project Plan & Final Design Review/Approval',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Final Design Review & Approval Phase \n\n🚀 You’ll receive all the page designs to review and approve before development begins. This ensures everything meets your expectations.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 6,
                'phase_id' => 10,
                'subject' => 'Project Discussion',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Project Discussion Phase \n\n🚀 We take time to walk you through the entire process to ensure alignment and address any final questions.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 7,
                'phase_id' => 11,
                'subject' => 'Slicing & Development',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Slicing & Development Phase \n\n🚀 Our developers begin coding your site — turning the approved designs into a functional, mobile-friendly website.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 8,
                'phase_id' => 12,
                'subject' => 'Initial Full Review',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Initial Full Review Phase \n\n🚀 Our QA team thoroughly checks the website for quality, functionality, and alignment with the agreed requirements.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 8,
                'phase_id' => 13,
                'subject' => 'Initial Full Review Fixes',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Initial Full Review Fixes Phase \n\n🚀 Any bugs or inconsistencies identified during the QA review are now being resolved by our developers.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 8,
                'phase_id' => 14,
                'subject' => 'Initial Full Review Fixes Verification',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Fixes Verification Phase \n\n🚀 QA re-tests the fixes to ensure everything has been properly addressed before proceeding to launch.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 9,
                'phase_id' => 15,
                'subject' => 'Review/Approval for Uploading & ask Hosting Credentials',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Review/Approval for Uploading Phase \n\n🚀 We prepare your website for live deployment and request final go-ahead from you along with any hosting details.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 9,
                'phase_id' => 16,
                'subject' => 'Devsite Client Comments',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Devsite Client Comments Phase \n\n🚀 You review the development version of your site and share your final feedback before we launch.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 9,
                'phase_id' => 17,
                'subject' => 'User/ Video Manual',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅User/Video Manual Phase \n\n🚀 We prepare a custom user manual or walkthrough video to help you manage your website post-launch.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 10,
                'phase_id' => 18,
                'subject' => 'Uploading/Launching',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Uploading/Launching Phase \n\n🚀 We launch your website to the live server and run final technical checks. Congratulations — you\'re now live!\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 11,
                'phase_id' => 19,
                'subject' => 'Final Full Review',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Final Full Review Phase \n\n🚀 Our QA team conducts a final walkthrough of your live website to ensure everything performs as expected.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 11,
                'phase_id' => 20,
                'subject' => 'Final Full Review Fixes',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Final Fixes Phase \n\n🚀 Our developers address any final issues post-launch to polish and finalize your site.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 11,
                'phase_id' => 21,
                'subject' => 'Final Full Review Fixes Verification',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Fixes Verification Phase \n\n🚀 Final QA to verify all post-launch updates are successful and the site is stable.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 12,
                'phase_id' => 22,
                'subject' => 'Review/Approval for Project Closure',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Review for Project Closure Phase \n\n🚀 We ask for your final confirmation to close the project. This ensures you\'re fully satisfied with the results.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 12,
                'phase_id' => 23,
                'subject' => 'Livesite client comments',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Livesite Client Comments Phase \n\n🚀 You have the opportunity to share any last observations or minor changes before we fully wrap up.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 11,
                'phase_id' => 24,
                'subject' => 'Project archiving',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Project Archiving Phase \n\n🚀 We securely archive your site’s files and documentation for future reference or backup needs.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'milestone_id' => 13,
                'phase_id' => 25,
                'subject' => 'Project Closure',
                'content' => 'Hi Client\nI hope you are doing well!\n\n\n We are now at the ✅Project Closure Phase \n\n🚀 The project is now complete! Thank you for your trust — we look forward to working with you again.\n\nMore Detalis: \n\nLet me know if you have questions or concerns. Thank you and have an amazing day!',
                'response' => "thank you",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('emails')->insert($emails);
    }
}
