<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\WebsiteStructure;

class WebsiteStructureSeeder extends Seeder
{
    public function run(): void
    {
        $structures = [
            [
                'section_type' => 'Top Navigational Bar ',
                'element' => "- Contact Information (Phone Number, Email Address) \n - Social Media Icons (Facebook, LinkedIn, Instagram) \n - Announcement Text (ex: \"Free Shipping!\")",
                'placeholder' => "- Phone: \"+1 (123) 456-7890\"\n- Email: \"info@example.com\"\n- Social: \"Facebook • LinkedIn • Instagram\"\n- Announcement: \"Now offering 24/7 support!\"",
                'functionality' => "- Clicking phone/email triggers call or mail app (on mobile/desktop)\n- Clicking social icons opens a new tab to social media\n- Scrolling keeps top bar sticky or hides on scroll (optional)",
                'deliverable' => "Given that I am visiting the Top Navigational Bar  section,\nWhen I interact with the Top Navigational Bar ,\n\nThen I should see all its elements; \n- Contact Information (Phone Number, Email Address) \n - Social Media Icons (Facebook, LinkedIn, Instagram) \n - Announcement Text (ex: \"Free Shipping!\")\n\nand then the Top Navigational Bar  should ba able to;\n- Clicking phone/email triggers call or mail app (on mobile/desktop)\n- Clicking social icons opens a new tab to social media\n- Scrolling keeps top bar sticky or hides on scroll (optional)",
                'video_manual' => "\"How to Update the Top Bar Contact Info, Social Links, and Announcement Text\"",
            ],
            [
                'section_type' => 'Header',
                'element' => "- Logo (usually at the left) \n - Navigation Menu Items (Home, About, Services, Blog, Contact) \n - Dropdown Menus (for Services or Products) \n - Call-to-Action Button (optional, like \"Book a Demo\", \"Get a Quote\")",
                'placeholder' => "- Logo: \"Company Logo\"\n- Menu Items: \"Home • About Us • Services • Blog • Contact\"\n- CTA Button: \"Get a Quote\"",
                'functionality' => "- Logo click redirects to homepage\n- Menu item click scrolls or navigates to the page\n- Hovering shows dropdowns\n- Clicking CTA Button opens form, scrolls down, or redirects",
                'deliverable' => "Given that I am visiting the Header section,\nWhen I interact with the Header,\n\nThen I should see all its elements; \n- Logo (usually at the left) \n - Navigation Menu Items (Home, About, Services, Blog, Contact) \n - Dropdown Menus (for Services or Products) \n - Call-to-Action Button (optional, like \"Book a Demo\", \"Get a Quote\")\n\nand then the Header should ba able to;\n- Logo click redirects to homepage\n- Menu item click scrolls or navigates to the page\n- Hovering shows dropdowns\n- Clicking CTA Button opens form, scrolls down, or redirects",
                'video_manual' => "\"How to Edit the Site Logo and Navigation Menu\"",
            ],
            [
                'section_type' => 'Hero Banner',
                'element' => "- Heading\n- Subheading\n- CTA Button\n- Background Image/Video",
                'placeholder' => "- Heading: \"Welcome to Our Company\"\n- Subheading: \"We Deliver Excellence Every Day\"\n- CTA Button: \"Learn More\"\n- Background: \"Background Image\"",
                'functionality' => "- Click CTA scrolls, opens form, or redirects\n- Video background plays/mutes\n- Smooth scroll on click",
                'deliverable' => "Given that I am visiting the Hero Banner section,\nWhen I interact with the Hero Banner,\n\nThen I should see all its elements; \n- Heading\n- Subheading\n- CTA Button\n- Background Image/Video\n\nand then the Hero Banner should ba able to;\n- Click CTA scrolls, opens form, or redirects\n- Video background plays/mutes\n- Smooth scroll on click",
                'video_manual' => "\"How to Edit the Hero Banner Heading, Subheading, Button, and Background Image\"",
            ],
            [
                'section_type' => 'Page Banner',
                'element' => "- Background Image\n- Page Title \n- Breadcrumb Navigation (Home > Page Name)\n- Short Subtitle or Description Text",
                'placeholder' => "- Page Title: \"Page Title\"\n- Breadcrumb: \"Home > Current Page\"\n- Subtitle: \"Discover more about our services\"\n- Background: \"Background Image\"",
                'functionality' => "- Background Image is static or has parallax scroll effect (optional)\n- Breadcrumb items are clickable links (except the current page)\n- Responsive resizing for mobile (title and breadcrumbs adjust)\n- Smooth scrolling or link navigation when breadcrumb is clicked",
                'deliverable' => "Given that I am visiting the Page Banner section,\nWhen I interact with the Page Banner,\n\nThen I should see all its elements; \n- Background Image\n- Page Title \n- Breadcrumb Navigation (Home > Page Name)\n- Short Subtitle or Description Text\n\nand then the Page Banner should ba able to;\n- Background Image is static or has parallax scroll effect (optional)\n- Breadcrumb items are clickable links (except the current page)\n- Responsive resizing for mobile (title and breadcrumbs adjust)\n- Smooth scrolling or link navigation when breadcrumb is clicked",
                'video_manual' => "\"How to Update the Page Banner Background Image, Title, and Breadcrumbs\"",
            ],
            [
                'section_type' => 'Introduction About',
                'element' => "- Section Title\n- Paragraph Text\n- Image/Illustration",
                'placeholder' => "- Section Title: \"Who We Are\"\n- Paragraph Text: \"We are committed to delivering top-quality solutions tailored to your needs.\"\n- Image: \"Placeholder Image\"",
                'functionality' => "- Scroll-triggered fade-in\n- Optional click to learn more",
                'deliverable' => "Given that I am visiting the Introduction About section,\nWhen I interact with the Introduction About,\n\nThen I should see all its elements; \n- Section Title\n- Paragraph Text\n- Image/Illustration\n\nand then the Introduction About should ba able to;\n- Scroll-triggered fade-in\n- Optional click to learn more",
                'video_manual' => "\"How to Edit the About Section Title, Text, and Image\"",
            ],
            [
                'section_type' => 'Services / Solutions Section - Display ',
                'element' => "- Service Icon\n- Service Title\n- Description\n- Learn More Button",
                'placeholder' => "- Service Title: \"Our Service Name\"\n- Description: \"Short description of the service offered.\"\n- Button: \"Learn More\"\n- Icon: \"Service Icon\"",
                'functionality' => "- Hover highlights service card\n- Click to view service detail\n- Displays only 3 service cards",
                'deliverable' => "Given that I am visiting the Services / Solutions Section - Display  section,\nWhen I interact with the Services / Solutions Section - Display ,\n\nThen I should see all its elements; \n- Service Icon\n- Service Title\n- Description\n- Learn More Button\n\nand then the Services / Solutions Section - Display  should ba able to;\n- Hover highlights service card\n- Click to view service detail\n- Displays only 3 service cards",
                'video_manual' => "\"How to Configure the Services Section Display Settings\"",
            ],
            [
                'section_type' => 'Services / Solutions Section  - Post Type',
                'element' => "- Category \n- Service Icon\n- Service Title\n- Description\n- Learn More Button\n- Pagination",
                'placeholder' => "- Service Title: \"Our Service Name\"\n- Description: \"Short description of the service offered.\"\n- Button: \"Learn More\"\n- Icon: \"Service Icon\"",
                'functionality' => "- Category will filter the service \n- Hover highlights service card\n- Click to view service detail\n- Maximum of 6 service cards per page",
                'deliverable' => "Given that I am visiting the Services / Solutions Section  - Post Type section,\nWhen I interact with the Services / Solutions Section  - Post Type,\n\nThen I should see all its elements; \n- Category \n- Service Icon\n- Service Title\n- Description\n- Learn More Button\n- Pagination\n\nand then the Services / Solutions Section  - Post Type should ba able to;\n- Category will filter the service \n- Hover highlights service card\n- Click to view service detail\n- Maximum of 6 service cards per page",
                'video_manual' => "\"How to Add, Edit, and Remove Services in the Services Post Type\"",
            ],
            [
                'section_type' => 'Features / Benefits - Display ',
                'element' => "- Feature Icon/Number\n- Feature Title\n- Supporting Text",
                'placeholder' => "- Feature Title: \"Why Choose Us\"\n- Supporting Text: \"We offer unparalleled value and results.\"\n- Icon/Number: \"Feature Icon/Number\"",
                'functionality' => "- Scroll-trigger animations\n- (Optional) Expandable features",
                'deliverable' => "Given that I am visiting the Features / Benefits - Display  section,\nWhen I interact with the Features / Benefits - Display ,\n\nThen I should see all its elements; \n- Feature Icon/Number\n- Feature Title\n- Supporting Text\n\nand then the Features / Benefits - Display  should ba able to;\n- Scroll-trigger animations\n- (Optional) Expandable features",
                'video_manual' => "\"How to Update Feature or Benefit Items\"",
            ],
            [
                'section_type' => 'Statistics / Counters',
                'element' => "- Animated Number\n- Label\n- Optional Icon",
                'placeholder' => "- Number: \"500+\"\n- Label: \"Successful Projects\"\n- Icon: \"Counter Icon\"",
                'functionality' => "- Animate counters on scroll into view",
                'deliverable' => "Given that I am visiting the Statistics / Counters section,\nWhen I interact with the Statistics / Counters,\n\nThen I should see all its elements; \n- Animated Number\n- Label\n- Optional Icon\n\nand then the Statistics / Counters should ba able to;\n- Animate counters on scroll into view",
                'video_manual' => "\"How to Edit and Animate Counter Numbers and Labels\"",
            ],
            [
                'section_type' => 'Portfolio / Case Studies - Display',
                'element' => "- Project Image\n- Project Title\n- Short Description\n- Link to Details",
                'placeholder' => "- Project Title: \"Project Name\"\n- Short Description: \"Brief overview of the project success story.\"\n- Link: \"View Details\"\n- Image: \"Placeholder Image\"",
                'functionality' => "- Hover effect on projects\n- Click to view full project or lightbox\n- Displays only 3 service cards",
                'deliverable' => "Given that I am visiting the Portfolio / Case Studies - Display section,\nWhen I interact with the Portfolio / Case Studies - Display,\n\nThen I should see all its elements; \n- Project Image\n- Project Title\n- Short Description\n- Link to Details\n\nand then the Portfolio / Case Studies - Display should ba able to;\n- Hover effect on projects\n- Click to view full project or lightbox\n- Displays only 3 service cards",
                'video_manual' => "\"How to Configure the Portfolio Section Display Settings\"",
            ],
            [
                'section_type' => 'Portfolio / Case Studies - Post Type',
                'element' => "- Category \n- Project Image\n- Project Title\n- Short Description\n- Link to Details\n- Pagination",
                'placeholder' => "- Project Title: \"Project Name\"\n- Short Description: \"Brief overview of the project success story.\"\n- Link: \"View Details\"\n- Image: \"Placeholder Image\"",
                'functionality' => "- Category will filter the case studies\n- Hover effect on projects\n- Click to view full project or lightbox\n- Maximum of 6 service cards per page",
                'deliverable' => "Given that I am visiting the Portfolio / Case Studies - Post Type section,\nWhen I interact with the Portfolio / Case Studies - Post Type,\n\nThen I should see all its elements; \n- Category \n- Project Image\n- Project Title\n- Short Description\n- Link to Details\n- Pagination\n\nand then the Portfolio / Case Studies - Post Type should ba able to;\n- Category will filter the case studies\n- Hover effect on projects\n- Click to view full project or lightbox\n- Maximum of 6 service cards per page",
                'video_manual' => "\"How to Add, Edit, and Remove Portfolio or Case Study Entries\"",
            ],
            [
                'section_type' => 'Team Section',
                'element' => "- Team Member Photo\n- Name\n- Position/Role\n- Short Bio\n- Pagination ",
                'placeholder' => "- Name: \"Jane Doe\"\n- Position: \"Chief Executive Officer\"\n- Bio: \"Passionate about innovation and leadership.\"\n- Photo: \"Placeholder Image\"",
                'functionality' => "- Hover zoom on photo\n- Click to view full profile (optional)\n- Maximum of 6 team member cards per page",
                'deliverable' => "Given that I am visiting the Team Section section,\nWhen I interact with the Team Section,\n\nThen I should see all its elements; \n- Team Member Photo\n- Name\n- Position/Role\n- Short Bio\n- Pagination \n\nand then the Team Section should ba able to;\n- Hover zoom on photo\n- Click to view full profile (optional)\n- Maximum of 6 team member cards per page",
                'video_manual' => "\"How to Add, Edit, and Remove Team Members\"",
            ],
            [
                'section_type' => 'Testimonials / Reviews',
                'element' => "- Quote/Testimonial Text\n- Client Name\n- Client Logo/Photo",
                'placeholder' => "- Quote: \"This team exceeded all expectations!\"\n- Client Name: \"John Smith\"\n- Position: \"Business Owner\"\n- Logo/Photo: \"Client Logo\"",
                'functionality' => "- Swipe carousel\n- Manual navigation arrows/dots",
                'deliverable' => "Given that I am visiting the Testimonials / Reviews section,\nWhen I interact with the Testimonials / Reviews,\n\nThen I should see all its elements; \n- Quote/Testimonial Text\n- Client Name\n- Client Logo/Photo\n\nand then the Testimonials / Reviews should ba able to;\n- Swipe carousel\n- Manual navigation arrows/dots",
                'video_manual' => "\"How to Manage Testimonials and Client Reviews\"",
            ],
            [
                'section_type' => 'Products or Packages - Display ',
                'element' => "- Product Image\n- Product Name\n- Price\n- Description\n- CTA Button",
                'placeholder' => "- Product Name: \"Product Name\"\n- Price: \"$99\"\n- Description: \"Brief description of the product.\"\n- Button: \"Buy Now\"\n- Image: \"Placeholder Image\"",
                'functionality' => "- Hover zoom on product\n- Click to buy/view details\n- Display only 3 Cards",
                'deliverable' => "Given that I am visiting the Products or Packages - Display  section,\nWhen I interact with the Products or Packages - Display ,\n\nThen I should see all its elements; \n- Product Image\n- Product Name\n- Price\n- Description\n- CTA Button\n\nand then the Products or Packages - Display  should ba able to;\n- Hover zoom on product\n- Click to buy/view details\n- Display only 3 Cards",
                'video_manual' => "\"How to Configure the Products or Packages Display Section\"",
            ],
            [
                'section_type' => 'Products or Packages - Post Type',
                'element' => "- Category \n- Product Image\n- Product Name\n- Price\n- Description\n- CTA Button\n- Pagination ",
                'placeholder' => "- Product Name: \"Product Name\"\n- Price: \"$99\"\n- Description: \"Brief description of the product.\"\n- Button: \"Buy Now\"\n- Image: \"Placeholder Image\"",
                'functionality' => "- Category will filter page\n- Hover zoom on product\n- Click to buy/view details\n- Maximum of 6 Cards per page",
                'deliverable' => "Given that I am visiting the Products or Packages - Post Type section,\nWhen I interact with the Products or Packages - Post Type,\n\nThen I should see all its elements; \n- Category \n- Product Image\n- Product Name\n- Price\n- Description\n- CTA Button\n- Pagination \n\nand then the Products or Packages - Post Type should ba able to;\n- Category will filter page\n- Hover zoom on product\n- Click to buy/view details\n- Maximum of 6 Cards per page",
                'video_manual' => "\"How to Add, Edit, and Remove Product Entries\"",
            ],
            [
                'section_type' => 'Blog Highlights / Resources - Display',
                'element' => "- Blog Post Image\n- Post Title\n- Excerpt\n- Read More Link",
                'placeholder' => "- Post Title: \"How to Improve Your Business\"\n- Excerpt: \"Discover strategies to elevate your company.\"\n- Link: \"Read More\"\n- Image: \"Placeholder Image\"",
                'functionality' => "- Hover effects\n- Click to open full blog post\n- Maximum 3 Cards per page",
                'deliverable' => "Given that I am visiting the Blog Highlights / Resources - Display section,\nWhen I interact with the Blog Highlights / Resources - Display,\n\nThen I should see all its elements; \n- Blog Post Image\n- Post Title\n- Excerpt\n- Read More Link\n\nand then the Blog Highlights / Resources - Display should ba able to;\n- Hover effects\n- Click to open full blog post\n- Maximum 3 Cards per page",
                'video_manual' => "\"How to Set Up Blog Post Highlights on the Frontend\"",
            ],
            [
                'section_type' => 'Blog Highlights / Resources - Post type',
                'element' => "- Category \n- Blog Post Image\n- Post Title\n- Excerpt\n- Read More Link\n- Pagination",
                'placeholder' => "- Post Title: \"How to Improve Your Business\"\n- Excerpt: \"Discover strategies to elevate your company.\"\n- Link: \"Read More\"\n- Image: \"Placeholder Image\"",
                'functionality' => "- Category will Filter page\n- Hover effects\n- Click to open full blog post\n- Maximum 6 Cards per page\n",
                'deliverable' => "Given that I am visiting the Blog Highlights / Resources - Post type section,\nWhen I interact with the Blog Highlights / Resources - Post type,\n\nThen I should see all its elements; \n- Category \n- Blog Post Image\n- Post Title\n- Excerpt\n- Read More Link\n- Pagination\n\nand then the Blog Highlights / Resources - Post type should ba able to;\n- Category will Filter page\n- Hover effects\n- Click to open full blog post\n- Maximum 6 Cards per page\n",
                'video_manual' => "\"How to Add, Edit, and Manage Blog Posts\"",
            ],
            [
                'section_type' => 'Video Section',
                'element' => "- Video Embed\n- Video Title\n- Short Description",
                'placeholder' => "- Video Title: \"Our Story\"\n- Description: \"Learn about our journey and values.\"\n- Video Embed: \"Video Placeholder\"",
                'functionality' => "- Play/Pause video\n- Fullscreen mode\n- Autoplay on scroll (optional)",
                'deliverable' => "Given that I am visiting the Video Section section,\nWhen I interact with the Video Section,\n\nThen I should see all its elements; \n- Video Embed\n- Video Title\n- Short Description\n\nand then the Video Section should ba able to;\n- Play/Pause video\n- Fullscreen mode\n- Autoplay on scroll (optional)",
                'video_manual' => "\"How to Add or Update a Video Embed\"",
            ],
            [
                'section_type' => 'Location / Map Section',
                'element' => "- Map Embed\n- Address\n- Directions",
                'placeholder' => "- Address: \"123 Main Street, City, Country\"\n- Map: \"Embedded Google Map\"",
                'functionality' => "- Zoom/pan map\n- Click for directions in maps app",
                'deliverable' => "Given that I am visiting the Location / Map Section section,\nWhen I interact with the Location / Map Section,\n\nThen I should see all its elements; \n- Map Embed\n- Address\n- Directions\n\nand then the Location / Map Section should ba able to;\n- Zoom/pan map\n- Click for directions in maps app",
                'video_manual' => "\"How to Update the Location Map and Address\"",
            ],
            [
                'section_type' => 'Contact Form Section',
                'element' => "- Form Fields (Name, Email, Message)\n- Checkbox for Privacy Policy and Terms and condition \n- Submit Button\n- Contact Info\n- Social Media Icons",
                'placeholder' => "- Name: \"Your Name\"\n- Email: \"your@email.com\"\n- Message: \"Type your message here...\"\n- Submit Button: \"Send Message\"",
                'functionality' => "- Name, Email is required\n- Check box is required \n- Form validation on submit\n- Success/Error messaging",
                'deliverable' => "Given that I am visiting the Contact Form Section section,\nWhen I interact with the Contact Form Section,\n\nThen I should see all its elements; \n- Form Fields (Name, Email, Message)\n- Checkbox for Privacy Policy and Terms and condition \n- Submit Button\n- Contact Info\n- Social Media Icons\n\nand then the Contact Form Section should ba able to;\n- Name, Email is required\n- Check box is required \n- Form validation on submit\n- Success/Error messaging",
                'video_manual' => "\"How to Edit the Contact Form Fields and Email Settings\"",
            ],
            [
                'section_type' => 'CTA Banner',
                'element' => "- Attention-Grabbing Text\n- CTA Button\n- Background Image/Color",
                'placeholder' => "- Eyebrow Text (optional): \"Ready to Start?\"\n- Heading: \"Let's Build Something Great Together\"\n- Button: \"Contact Us Today\"\n- Background: \"Background Image\"",
                'functionality' => "- Click CTA to scroll or redirect\n- Background parallax/hover effects",
                'deliverable' => "Given that I am visiting the CTA Banner section,\nWhen I interact with the CTA Banner,\n\nThen I should see all its elements; \n- Attention-Grabbing Text\n- CTA Button\n- Background Image/Color\n\nand then the CTA Banner should ba able to;\n- Click CTA to scroll or redirect\n- Background parallax/hover effects",
                'video_manual' => "\"How to Update CTA Banner Text, Button, and Background Image\"",
            ],
            [
                'section_type' => 'Partners / Logos Carousel',
                'element' => "- Partner/Client Logos\n- Section Title (optional)",
                'placeholder' => "- Section Title: \"Our Trusted Partners\"\n- Logos: \"Partner Logos\"",
                'functionality' => "- Auto-rotating carousel\n- Manual swipe/click logos\n- Optional link to partner site",
                'deliverable' => "Given that I am visiting the Partners / Logos Carousel section,\nWhen I interact with the Partners / Logos Carousel,\n\nThen I should see all its elements; \n- Partner/Client Logos\n- Section Title (optional)\n\nand then the Partners / Logos Carousel should ba able to;\n- Auto-rotating carousel\n- Manual swipe/click logos\n- Optional link to partner site",
                'video_manual' => "\"How to Add and Manage Partner or Client Logos\"",
            ],
            [
                'section_type' => 'Awards / Certifications',
                'element' => "- Award Badge Image\n- Award Title\n- Description (optional)",
                'placeholder' => "- Award Title: \"Best Innovator Award 2024\"\n- Description: \"Recognized for excellence in technology solutions.\"\n- Badge Image: \"Award Badge Placeholder\"",
                'functionality' => "- Hover glow effect\n- (Optional) click to see more about award",
                'deliverable' => "Given that I am visiting the Awards / Certifications section,\nWhen I interact with the Awards / Certifications,\n\nThen I should see all its elements; \n- Award Badge Image\n- Award Title\n- Description (optional)\n\nand then the Awards / Certifications should ba able to;\n- Hover glow effect\n- (Optional) click to see more about award",
                'video_manual' => "\"How to Add and Edit Award or Certification Entries\"",
            ],
            [
                'section_type' => 'Timeline / History Section',
                'element' => "- Timeline Points\n- Dates\n- Event Descriptions",
                'placeholder' => "- Date: \"2020\"\n- Event Description: \"Company founded with a vision to innovate.\"",
                'functionality' => "- Scroll/Click through timeline\n- Animated progress line",
                'deliverable' => "Given that I am visiting the Timeline / History Section section,\nWhen I interact with the Timeline / History Section,\n\nThen I should see all its elements; \n- Timeline Points\n- Dates\n- Event Descriptions\n\nand then the Timeline / History Section should ba able to;\n- Scroll/Click through timeline\n- Animated progress line",
                'video_manual' => "\"How to Manage Timeline or Company History Entries\"",
            ],
            [
                'section_type' => 'FAQ Accordion Section',
                'element' => "- Question\n- Expandable Answer",
                'placeholder' => "- Question: \"What services do you offer?\"\n- Answer: \"We provide a range of IT solutions tailored to your needs.\n",
                'functionality' => "- Click question to expand/collapse answer",
                'deliverable' => "Given that I am visiting the FAQ Accordion Section section,\nWhen I interact with the FAQ Accordion Section,\n\nThen I should see all its elements; \n- Question\n- Expandable Answer\n\nand then the FAQ Accordion Section should ba able to;\n- Click question to expand/collapse answer",
                'video_manual' => "\"How to Add and Manage FAQs in the Accordion\"",
            ],
            [
                'section_type' => 'Pricing Tables',
                'element' => "- Plan Name\n- Price\n- Features List\n- CTA Button",
                'placeholder' => "- Plan Name: \"Starter Plan\"\n- Price: \"$49/month\"\n- Features List: \"Feature 1, Feature 2, Feature 3\"\n- Button: \"Choose Plan\"",
                'functionality' => "- Hover highlight\n- Click select plan to redirect or checkout",
                'deliverable' => "Given that I am visiting the Pricing Tables section,\nWhen I interact with the Pricing Tables,\n\nThen I should see all its elements; \n- Plan Name\n- Price\n- Features List\n- CTA Button\n\nand then the Pricing Tables should ba able to;\n- Hover highlight\n- Click select plan to redirect or checkout",
                'video_manual' => "\"How to Update Pricing Plans and Features\"",
            ],
            [
                'section_type' => 'Footer',
                'element' => "- Footer Menu Links\n- Social Icons\n- Copyright Text\n- Quick Links (Privacy Policy, Terms and Condition)",
                'placeholder' => "- Footer Links: \"Privacy Policy • Terms & Conditions\"\n- Social Media Links: \"Facebook • LinkedIn • Instagram\"\n- Copyright: \"© 2025 Your Company. All rights reserved.\"",
                'functionality' => "- Click links to navigate\n- Open social links in new tab",
                'deliverable' => "Given that I am visiting the Footer section,\nWhen I interact with the Footer,\n\nThen I should see all its elements; \n- Footer Menu Links\n- Social Icons\n- Copyright Text\n- Quick Links (Privacy Policy, Terms and Condition)\n\nand then the Footer should ba able to;\n- Click links to navigate\n- Open social links in new tab",
                'video_manual' => "\"How to Edit Footer Links, Social Icons, and Quick Links\"",
            ],
        ];

        foreach ($structures as $structure) {
            WebsiteStructure::create($structure);
        }
    }
}
